# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  alternative_assembly_types:
    - 
      key: local_groups # used to search a I18n key and a route path
      position_in_menu: 2.6
      assembly_type_ids: [5]
  scoped_participatory_process_slug_prefixes:
    -
      key: general_assemblies # used to search a I18n key and a route path
      position_in_menu: 2.6
      slug_prefixes: ["SomAG"]
  omniauth:
    facebook:
      # It must be a boolean. Remember ENV variables doesn't support booleans.
      enabled: false
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    twitter:
      enabled: false
      api_key: <%= ENV["OMNIAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OMNIAUTH_TWITTER_API_SECRET"] %>
    google_oauth2:
      enabled: false
      client_id: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] %>
  maps:
    api_key: <%= ENV["HERE_API_KEY"] %>
  etherpad:
    server: <%= ENV["ETHERPAD_SERVER"] %>
    api_key: <%= ENV["ETHERPAD_API_KEY"] %>
    api_version: "1.2.1"
  matomo:
    url: //matomo.participa.somenergia.coop/
    id: <%= ENV["MATOMO_ID"] %>    
  menu:
    localhost:
      - key: somenergia.menu.team_et
        url: /assemblies/nulla-aut
        position: 10
        if_membership_in: nulla-aut
    prod.participa.somenergia.coop:
      - key: somenergia.menu.team_et
        url: /assemblies/et
        position: 10
        if_membership_in: et
    staging.participa.somenergia.coop:
      - key: somenergia.menu.team_et
        url: /assemblies/et
        position: 10
        if_membership_in: et
    participa.somenergia.coop:
      - key: somenergia.menu.team_et
        url: /assemblies/et
        position: 10
        if_membership_in: et

development:
  <<: *default
  secret_key_base: 90d17c079bb42e0d52d9a33a8e59eacd887ba2b0c0da5e0792354cb82ac9f94fee61c1b503b81211d9b98cd8aa0f292b8bf3c1126773fa17211391ba2af998f5

test:
  <<: *default
  secret_key_base: 9f93fabe88fd2169da4ad6f3f535c3056260fa95392573312a331134b3c47e5ba3231d0b5a97a17972ca6a03a67af7714ca37cc7b2055b2237a15943d1a86525
  omniauth:
    facebook:
      enabled: true
    twitter:
      enabled: true
    google_oauth2:
      enabled: true
  matomo:
    url: //matomo.lvh.me
    id: 123

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sendgrid: <%= !ENV["SENDGRID_USERNAME"].blank? %>
  smtp_username: <%= ENV["MAILER_SMTP_USER_NAME"] || ENV["SENDGRID_USERNAME"] %>
  smtp_password: <%= ENV["MAILER_SMTP_PASSWORD"] || ENV["SENDGRID_PASSWORD"] %>
  smtp_address: <%= ENV["MAILER_SMTP_ADDRESS"] || "smtp.sendgrid.net" %>
  smtp_domain: <%= ENV["MAILER_SMTP_DOMAIN"] || "heroku.com" %>
  smtp_port: <%= ENV["MAILER_SMTP_PORT"] || "587" %>
  smtp_starttls_auto: true
  smtp_authentication: "plain"
